name: 00 - Main CI / CD Pipeline

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit #https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

  sca:
    needs: build
    name: SCA
    uses: ./.github/workflows/sca.yml
    secrets: inherit
    
  license-compliance:
    needs: build
    name: License compliance
    uses: ./.github/workflows/license-compliance.yml
    secrets: inherit
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
